#!/usr/bin/env python3
"""Canonical game identity: CFBD <-> Odds API.

Builds a deterministic cross-source identity layer with explicit states:
- MATCHED: exactly one CFBD game matches one Odds API event
- AMBIGUOUS: multiple candidates (requires manual review, never auto-resolved)
- UNMATCHED_ODDS: Odds API event with no CFBD counterpart
- UNMATCHED_CFBD: CFBD game with no Odds API counterpart

No silent fuzzy matching. All normalizations are explicit and logged.

This is shared infrastructure for: outcomes, weather, play-by-play,
model evaluation, and future market research.

Read-only on source tables. Writes mapping to ncaaf_game_identity.
"""
import os, sys, json, argparse, re
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
CFBD_PATH = HERE / "cfbd_2022_2024.json"
ALIASES_PATH = HERE / "team_aliases.json"

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sports  # noqa: E402


def load_aliases():
    """Load explicit Odds API -> CFBD team name aliases.

    Built deterministically from observed data:
    - 244 auto-generated by stripping 1-2 word mascots
    - 12 manual for naming differences (App State, Hawai'i, UAlbany, etc.)
    No silent fuzzy matching; all aliases are explicit in team_aliases.json.
    """
    if ALIASES_PATH.exists():
        with open(ALIASES_PATH) as f:
            return json.load(f)
    return {}


def normalize_team(name, aliases=None):
    """Explicit team name normalization with alias resolution.

    1. Check explicit alias table first (Odds API -> CFBD)
    2. Then apply text normalization (lowercase, strip, etc.)
    All aliases are explicit in team_aliases.json; no fuzzy matching.
    """
    if not name:
        return ""
    # Resolve alias first
    if aliases and name in aliases:
        name = aliases[name]
    # Lowercase, strip
    n = name.lower().strip()
    # Remove common suffixes/prefixes (EXPLICIT list)
    # Note: "state" is significant (Ohio State vs Ohio) — do not strip
    replacements = [
        ("university of ", ""),
        ("univ. ", ""),
        (" college", ""),
        # Keep "st." as "state" vs "saint" ambiguous — log, don't guess
    ]
    for old, new in replacements:
        n = n.replace(old, new)
    # Remove punctuation, collapse whitespace
    n = re.sub(r'[^a-z0-9 ]', '', n)
    n = re.sub(r'\s+', ' ', n).strip()
    return n


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--sport", default="ncaaf")
    ap.add_argument("--seasons", default="2022,2023,2024")
    ap.add_argument("--out", default="/tmp/canonical_identity.json")
    ap.add_argument("--cfbd-file", default=None,
                    help="Path to CFBD games JSON (for local testing)")
    args = ap.parse_args(argv)

    seasons = [int(s) for s in args.seasons.split(",")]

    # Load explicit team aliases (Odds API -> CFBD)
    aliases = load_aliases()
    print(f"Loaded {len(aliases)} team aliases", file=sys.stderr)

    # Load CFBD games
    # Priority: --cfbd-file arg > bundled reference file (resolved relative
    # to this script, not the working directory) > live API fetch
    bundled = str(CFBD_PATH) if CFBD_PATH.exists() else None
    print(f"Bundled CFBD path: {CFBD_PATH}", file=sys.stderr)
    print(f"Exists: {CFBD_PATH.exists()}", file=sys.stderr)
    cfbd_source = args.cfbd_file or bundled
    if cfbd_source:
        print(f"Loading CFBD from {cfbd_source}...", file=sys.stderr)
        with open(cfbd_source) as f:
            cfbd_games = json.load(f)
        print(f"CFBD: loaded {len(cfbd_games)} games from {cfbd_source}",
              file=sys.stderr)
    else:
        # Fetch from CFBD API
        sys.path.insert(0, os.path.expanduser("~/workspace/skills/collegefootballdata/bin"))
        # Import and fetch
        import urllib.request
        sys.path.insert(0, "/opt/hatch/skills/skill-creator/bin")
        import dynamic_credentials as dc
        cfbd_games = []
        for year in seasons:
            for st in ["regular", "postseason"]:
                url = f"https://api.collegefootballdata.com/games?year={year}&seasonType={st}"
                req = urllib.request.Request(url)
                dc.add_surrogate_to_request(
                    req, "custom.collegefootballdata",
                    allowed_hosts=["api.collegefootballdata.com"])
                with urllib.request.urlopen(req, timeout=30) as resp:
                    games = dc.read_json_response(resp)
                cfbd_games.extend(games)
                print(f"CFBD: year={year} {st}: {len(games)} games", file=sys.stderr)

    # Load Odds API events from market_history JSON payloads
    # (team names are in the raw snapshot envelopes, not quote columns)
    # Envelope structure: {"timestamp": ..., "data": [{id, home_team, away_team, commence_time, ...}]}
    import psycopg
    dsn = os.environ.get("NFL_EDGE_DATABASE_URL")
    hq = sports.historical_quotes_table(args.sport)
    mh = sports.market_history_table(args.sport)
    with psycopg.connect(dsn) as conn:
        # Extract events from payload->'data' array
        # (confirmed via direct Neon inspection 2026-09-15)
        rows = conn.execute(f"""
            SELECT DISTINCT
                event->>'id' AS odds_event_id,
                event->>'home_team' AS home_team,
                event->>'away_team' AS away_team,
                (event->>'commence_time')::timestamptz AS commence_time
            FROM public.{mh} mh
            CROSS JOIN LATERAL jsonb_array_elements(mh.payload->'data') AS event
            WHERE event->>'id' IS NOT NULL
              AND event->>'home_team' IS NOT NULL
              AND event->>'away_team' IS NOT NULL
              AND event->>'commence_time' IS NOT NULL
        """).fetchall()
        odds_events = []
        for r in rows:
            eid, home, away, kickoff = r
            odds_events.append({
                "event_id": eid, "home": home, "away": away, "kickoff": kickoff
            })

    print(f"Odds API events: {len(odds_events)}", file=sys.stderr)
    print(f"CFBD games: {len(cfbd_games)}", file=sys.stderr)

    # Build indices
    # CFBD: (date, normalized_home, normalized_away) -> game
    cfbd_index = defaultdict(list)
    for g in cfbd_games:
        if g.get("season") not in seasons:
            continue
        # Parse date
        sd = g.get("startDate", "")
        date_key = sd[:10] if sd else ""
        home = normalize_team(g.get("homeTeam", ""))
        away = normalize_team(g.get("awayTeam", ""))
        # Also index swapped (in case home/away flipped)
        cfbd_index[(date_key, home, away)].append(g)
        # Don't auto-index swapped — that's a separate match attempt

    # Match
    results = {
        "matched": [],
        "ambiguous": [],
        "unmatched_odds": [],
        "unmatched_cfbd": [],
    }
    matched_cfbd_ids = set()

    for oe in odds_events:
        kickoff = oe.get("kickoff")
        if hasattr(kickoff, "strftime"):
            date_key = kickoff.strftime("%Y-%m-%d")
        else:
            date_key = str(kickoff)[:10] if kickoff else ""

        home = normalize_team(oe.get("home", ""), aliases)
        away = normalize_team(oe.get("away", ""), aliases)
        # Track if alias was used
        home_aliased = oe.get("home", "") in aliases
        away_aliased = oe.get("away", "") in aliases

        # Try exact match
        candidates = cfbd_index.get((date_key, home, away), [])

        # Try swapped (neutral site or data entry variation)
        if not candidates:
            candidates = cfbd_index.get((date_key, away, home), [])

        if len(candidates) == 1:
            cg = candidates[0]
            # Determine match type
            if (date_key, home, away) in cfbd_index:
                mtype = "alias" if (home_aliased or away_aliased) else "exact"
            else:
                mtype = "swapped"
            results["matched"].append({
                "provider_event_id": oe["event_id"],
                "cfbd_id": cg["id"],
                "date": date_key,
                "odds_home": oe.get("home"),
                "odds_away": oe.get("away"),
                "cfbd_home": cg.get("homeTeam"),
                "cfbd_away": cg.get("awayTeam"),
                "match_type": mtype,
            })
            matched_cfbd_ids.add(cg["id"])
        elif len(candidates) > 1:
            results["ambiguous"].append({
                "provider_event_id": oe["event_id"],
                "candidates": [
                    {"cfbd_id": c["id"], "home": c.get("homeTeam"),
                     "away": c.get("awayTeam"), "date": c.get("startDate")}
                    for c in candidates
                ],
            })
        else:
            results["unmatched_odds"].append({
                "provider_event_id": oe["event_id"],
                "date": date_key,
                "home": oe.get("home"),
                "away": oe.get("away"),
            })

    # Unmatched CFBD
    for g in cfbd_games:
        if g.get("season") not in seasons:
            continue
        if g["id"] not in matched_cfbd_ids:
            # Only count FBS games (avoid FCS noise)
            # Check classification (may be None in CFBD JSON)
            hc = g.get("homeClassification") or ""
            ac = g.get("awayClassification") or ""
            if "fbs" in hc.lower() or "fbs" in ac.lower():
                results["unmatched_cfbd"].append({
                    "cfbd_id": g["id"],
                    "date": g.get("startDate", "")[:10],
                    "home": g.get("homeTeam"),
                    "away": g.get("awayTeam"),
                })

    # Statistics
    stats = {
        "n_odds_events": len(odds_events),
        "n_cfbd_games": len([g for g in cfbd_games if g.get("season") in seasons]),
        "n_matched": len(results["matched"]),
        "n_ambiguous": len(results["ambiguous"]),
        "n_unmatched_odds": len(results["unmatched_odds"]),
        "n_unmatched_cfbd": len(results["unmatched_cfbd"]),
        "match_rate": (len(results["matched"]) / len(odds_events)
                       if odds_events else 0),
    }

    output = {
        "methodology": (
            "Deterministic matching on (date, normalized_home, normalized_away). "
            "Team names resolved via explicit alias table (team_aliases.json) "
            "before text normalization. No fuzzy matching. Swapped home/away "
            "tried as separate attempt. Ambiguous matches require manual review."
        ),
        "normalization_rules": [
            "1. Explicit alias lookup (Odds API -> CFBD), 256 aliases",
            "2. lowercase, strip whitespace",
            "3. remove 'university of ', 'univ. ', ' college'",
            "4. remove punctuation, collapse whitespace",
            "NOTE: 'state' preserved (Ohio State != Ohio)",
            "NOTE: 'st.' not normalized (Saint vs State ambiguous)",
            "NOTE: 244 aliases auto-generated by stripping 1-2 word mascots",
            "NOTE: 12 manual aliases for naming differences (App State, Hawai'i, etc.)",
        ],
        "stats": stats,
        "results": results,
    }

    with open(args.out, "w") as f:
        json.dump(output, f, indent=2)

    print(json.dumps(stats, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
